# Generated by Django 5.1.4 on 2024-12-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='backgroud_color',
            field=models.CharField(default='bg-blue-200', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='left_bg',
            field=models.CharField(default='bg-blue-400', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='right_bg',
            field=models.CharField(default='bg-blue-300', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='text_color',
            field=models.CharField(default='white', max_length=100),
        ),
    ]
